FROM haxe:4.3.6

ENV LANG=en_US.utf8
ENV LANGUAGE=en_US.UTF-8

RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y locales locales-all

# Mono / C#
RUN apt install gnupg ca-certificates
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list
RUN apt update
RUN apt install -y mono-devel

# Install C++
RUN yes | apt-get install -y gcc
RUN yes | apt-get install -y g++

# Install NodeJS
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ENV NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install -y nodejs

ENV NODE_PATH=/usr/lib/node_modules
ENV NODE_OPTIONS=--max_old_space_size=4096

# Install Java
RUN apt-get install -y default-jdk
ENV JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"

# Install PHP
RUN apt install -y php libapache2-mod-php php-cli php-gd php-mbstring

# Install Python
RUN apt-get install -y python3 python3-pip

# Install Haxe Libs
RUN haxelib setup /haxelib
RUN yes | haxelib install hxcpp
RUN yes | haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git
RUN yes | haxelib install hxjava
RUN yes | haxelib install hxcs

RUN apt-get install -y make

RUN mkdir /workspace
WORKDIR /workspace

CMD ["tail", "-f", "/dev/null"]
